name: Publish
on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: Release Type
        options:
          - release
          - prerelease
          - graduate

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: 'lannonbr/repo-permission-check-action@2.0.2'
        with:
          permission: 'write'
        env:
          GITHUB_TOKEN: ${{ secrets.GITUH_PUBLISH_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [authorize]
    permissions:
      id-token: write
      contents: write
    env:
      RELEASE_TYPE: ${{ github.event.inputs.releaseType }}
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Configure Git User
        run: |
          git config --global user.name kevinpagtakhan
          git config --global user.email kevpagtakhan@gmail.com

      - name: Configure NPM User
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami

      # https://www.npmjs.com/package/@lerna/version#--conventional-prerelease
      # patch: 1.0.0 -> 1.0.1-alpha.0
      # minor: 1.0.0 -> 1.1.0-alpha.0
      # major: 1.0.0 -> 2.0.0-alpha.0
      - name: Create pre-release version
        if: ${{ env.RELEASE_TYPE == 'prerelease'}}
        run: |
          npm run lerna:version -- -y --conventional-prerelease

      # https://www.npmjs.com/package/@lerna/version#--conventional-graduate
      # 1.0.0-alpha.0 -> 1.0.1
      - name: Create graduate version
        if: ${{ env.RELEASE_TYPE == 'graduate'}}
        run: |
          npm run lerna:version -- -y --conventional-graduate

      # Use 'release' for the usual deployment
      # NOTE: You probably want this
      - name: Create release version
        if: ${{ env.RELEASE_TYPE == 'release'}}
        run: |
          npm run lerna:version -- -y

      # Use 'from git' option if `lerna version` has already been run
      - name: Publish Release to NPM
        run: |
          npm run lerna:publish -- from-git -y
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
